// Code generated by qtc from "admin_edit.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/admin_edit.qtpl:1
package templates

//line internal/web/templates/admin_edit.qtpl:1
import (
	"github.com/holedaemon/turnttable/internal/db/models"
)

//line internal/web/templates/admin_edit.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/admin_edit.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/admin_edit.qtpl:6
type AdminEditPage struct {
	BasePage
	Record *models.Record
}

//line internal/web/templates/admin_edit.qtpl:12
func (p *AdminEditPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/admin_edit.qtpl:12
	qw422016.N().S(`Edit Record`)
//line internal/web/templates/admin_edit.qtpl:12
}

//line internal/web/templates/admin_edit.qtpl:12
func (p *AdminEditPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/admin_edit.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/admin_edit.qtpl:12
	p.StreamTitle(qw422016)
//line internal/web/templates/admin_edit.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/admin_edit.qtpl:12
}

//line internal/web/templates/admin_edit.qtpl:12
func (p *AdminEditPage) Title() string {
//line internal/web/templates/admin_edit.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/admin_edit.qtpl:12
	p.WriteTitle(qb422016)
//line internal/web/templates/admin_edit.qtpl:12
	qs422016 := string(qb422016.B)
//line internal/web/templates/admin_edit.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/admin_edit.qtpl:12
	return qs422016
//line internal/web/templates/admin_edit.qtpl:12
}

//line internal/web/templates/admin_edit.qtpl:14
func (p *AdminEditPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/admin_edit.qtpl:14
	qw422016.N().S(`
<form method="post">
    <div class="columns is-multiline mx-1">
        <div class="column is-half">
            <div class="field">
                <label class="label has-text-white-ter">Release Title</label>
                <div class="control">
                    <input class="input" type="text" name="title" placeholder="Release Title" value="`)
//line internal/web/templates/admin_edit.qtpl:21
	qw422016.E().S(p.Record.Title)
//line internal/web/templates/admin_edit.qtpl:21
	qw422016.N().S(`" required>
                </div>
            </div>
        </div>
        <div class="column is-half">
            <div class="field">
                <label class="label has-text-white-ter">Artist</label>
                <div class="control">
                    <input class="input" type="text" name="artist" placeholder="Artist" value="`)
//line internal/web/templates/admin_edit.qtpl:29
	qw422016.E().S(p.Record.Artist)
//line internal/web/templates/admin_edit.qtpl:29
	qw422016.N().S(`" required>
                </div>
            </div>
        </div>
        <div class="column is-half">
            <div class="field">
                <label class="label has-text-white-ter">Label</label>
                <div class="control">
                    <input class="input" type="text" name="label" placeholder="Label" value="`)
//line internal/web/templates/admin_edit.qtpl:37
	qw422016.E().S(p.Record.Label)
//line internal/web/templates/admin_edit.qtpl:37
	qw422016.N().S(`" required>
                </div>
            </div>
        </div>
        <div class="column is-half">
            <div class="field">
                <label class="label has-text-white-ter">Catalogue Number</label>
                <div class="control">
                    <input class="input" type="text" name="cn" placeholder="Catalogue Number" value="`)
//line internal/web/templates/admin_edit.qtpl:45
	qw422016.E().S(p.Record.CN)
//line internal/web/templates/admin_edit.qtpl:45
	qw422016.N().S(`" required>
                </div>
            </div>
        </div>
        <div class="column is-half">
            <div class="field">
                <label class="label has-text-white-ter">Genre</label>
                <div class="control">
                    <input class="input" type="text" name="genre" placeholder="Genre" value="`)
//line internal/web/templates/admin_edit.qtpl:53
	qw422016.E().S(p.Record.Genre)
//line internal/web/templates/admin_edit.qtpl:53
	qw422016.N().S(`" required>
                </div>
            </div>
        </div>
        <div class="column is-half">
            <div class="field">
                <label class="label has-text-white-ter">Released</label>
                <div class="control">
                    <input class="input" type="date" name="release" value="`)
//line internal/web/templates/admin_edit.qtpl:61
	qw422016.E().S(p.Record.Released.Format("2006-01-02"))
//line internal/web/templates/admin_edit.qtpl:61
	qw422016.N().S(`" required>
                </div>
            </div>
        </div>
        <div class="column is-half">
            <div class="field">
                <label class="label has-text-white-ter">Purchased</label>
                <div class="control">
                    <input class="input" type="date" name="purchased" value="`)
//line internal/web/templates/admin_edit.qtpl:69
	qw422016.E().S(p.Record.Purchased.Time.Format("2006-01-02"))
//line internal/web/templates/admin_edit.qtpl:69
	qw422016.N().S(`">
                </div>
            </div>
        </div>
        <div class="column is-one-quarter">
            <div class="field">
                <label class="label has-text-white-ter">Medium</label>
                <div class="control">
                    <div class="select">
                        <select name="medium">
                            <option value="cd" `)
//line internal/web/templates/admin_edit.qtpl:79
	if p.Record.Medium == models.MediumCD {
//line internal/web/templates/admin_edit.qtpl:79
		qw422016.N().S(` selected `)
//line internal/web/templates/admin_edit.qtpl:79
	}
//line internal/web/templates/admin_edit.qtpl:79
	qw422016.N().S(`>CD</option>
                            <option value="vinyl" `)
//line internal/web/templates/admin_edit.qtpl:80
	if p.Record.Medium == models.MediumVinyl {
//line internal/web/templates/admin_edit.qtpl:80
		qw422016.N().S(` selected `)
//line internal/web/templates/admin_edit.qtpl:80
	}
//line internal/web/templates/admin_edit.qtpl:80
	qw422016.N().S(`>Vinyl</option>
                            <option value="cassette" `)
//line internal/web/templates/admin_edit.qtpl:81
	if p.Record.Medium == models.MediumCassette {
//line internal/web/templates/admin_edit.qtpl:81
		qw422016.N().S(` selected `)
//line internal/web/templates/admin_edit.qtpl:81
	}
//line internal/web/templates/admin_edit.qtpl:81
	qw422016.N().S(`>Cassette</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="columns mx-1">
        <div class="column is-one-quarter">
            <div class="field">
                <div class="control">
                    <button class="button is-primary">Submit</button>
                </div>
            </div>
        </div>
    </div>
</form>
`)
//line internal/web/templates/admin_edit.qtpl:98
}

//line internal/web/templates/admin_edit.qtpl:98
func (p *AdminEditPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/admin_edit.qtpl:98
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/admin_edit.qtpl:98
	p.StreamBody(qw422016)
//line internal/web/templates/admin_edit.qtpl:98
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/admin_edit.qtpl:98
}

//line internal/web/templates/admin_edit.qtpl:98
func (p *AdminEditPage) Body() string {
//line internal/web/templates/admin_edit.qtpl:98
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/admin_edit.qtpl:98
	p.WriteBody(qb422016)
//line internal/web/templates/admin_edit.qtpl:98
	qs422016 := string(qb422016.B)
//line internal/web/templates/admin_edit.qtpl:98
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/admin_edit.qtpl:98
	return qs422016
//line internal/web/templates/admin_edit.qtpl:98
}
