// Code generated by qtc from "admin.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package templates

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

type AdminPage struct {
	BasePage
}

func (p *AdminPage) StreamTitle(qw422016 *qt422016.Writer) {
	qw422016.N().S(`Admin Dashboard`)
}

func (p *AdminPage) WriteTitle(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamTitle(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *AdminPage) Title() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteTitle(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}

func (p *AdminPage) StreamBody(qw422016 *qt422016.Writer) {
	qw422016.N().S(`
<div class="columns is-centered">
    <div class="column is-narrow">
        <a class="button is-primary is-large" href="/admin/insert">Insert</a>
    </div>
    <div class="column is-narrow">
        <a class="button is-primary is-large" href="/admin/insert/bulk">Bulk Insert</a>
    </div>
    <div class="column is-narrow">
        <a class="button is-primary is-large" href="/admin/alter">Alter</a>
    </div>
</div>
`)
}

func (p *AdminPage) WriteBody(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	p.StreamBody(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func (p *AdminPage) Body() string {
	qb422016 := qt422016.AcquireByteBuffer()
	p.WriteBody(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
