// Code generated by qtc from "admin.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:1
package templates

//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:2
type AdminPage struct {
	BasePage
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
func (p *AdminPage) StreamTitle(qw422016 *qt422016.Writer) {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
	qw422016.N().S(`Admin Dashboard`)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
func (p *AdminPage) WriteTitle(qq422016 qtio422016.Writer) {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
	p.StreamTitle(qw422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
func (p *AdminPage) Title() string {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
	p.WriteTitle(qb422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
	qs422016 := string(qb422016.B)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
	return qs422016
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:7
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:9
func (p *AdminPage) StreamBody(qw422016 *qt422016.Writer) {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:9
	qw422016.N().S(`
<div class="columns is-centered">
    <div class="column is-narrow">
        <a class="button is-primary is-large" href="/admin/insert">Insert</a>
    </div>
    <div class="column is-narrow">
        <a class="button is-primary is-large" href="/admin/insert/bulk">Bulk Insert</a>
    </div>
    <div class="column is-narrow">
        <a class="button is-primary is-large" href="/admin/alter">Alter</a>
    </div>
</div>
`)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
func (p *AdminPage) WriteBody(qq422016 qtio422016.Writer) {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
	p.StreamBody(qw422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
func (p *AdminPage) Body() string {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
	p.WriteBody(qb422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
	qs422016 := string(qb422016.B)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
	return qs422016
//line /home/max/git/holedaemon/turnttable/internal/web/templates/admin.qtpl:21
}
