// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/base.qtpl:1
package templates

//line internal/web/templates/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/base.qtpl:1
type Page interface {
//line internal/web/templates/base.qtpl:1
	Title() string
//line internal/web/templates/base.qtpl:1
	StreamTitle(qw422016 *qt422016.Writer)
//line internal/web/templates/base.qtpl:1
	WriteTitle(qq422016 qtio422016.Writer)
//line internal/web/templates/base.qtpl:1
	Body() string
//line internal/web/templates/base.qtpl:1
	StreamBody(qw422016 *qt422016.Writer)
//line internal/web/templates/base.qtpl:1
	WriteBody(qq422016 qtio422016.Writer)
//line internal/web/templates/base.qtpl:1
	Meta() string
//line internal/web/templates/base.qtpl:1
	StreamMeta(qw422016 *qt422016.Writer)
//line internal/web/templates/base.qtpl:1
	WriteMeta(qq422016 qtio422016.Writer)
//line internal/web/templates/base.qtpl:1
}

//line internal/web/templates/base.qtpl:8
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line internal/web/templates/base.qtpl:8
	qw422016.N().S(`
<html class="has-background-dark has-text-light">
    <head>
        <title>turnttable &bull; `)
//line internal/web/templates/base.qtpl:11
	p.StreamTitle(qw422016)
//line internal/web/templates/base.qtpl:11
	qw422016.N().S(`</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

        `)
//line internal/web/templates/base.qtpl:16
	p.StreamMeta(qw422016)
//line internal/web/templates/base.qtpl:16
	qw422016.N().S(`
    </head>
    <body>
        <div class="container">
             <nav class="navbar is-dark mb-5" role="navigation" aria-label="main navigation">
                <div class="navbar-brand">
                    <a class="navbar-item is-size-4" href="/">
                        turnttable
                    </a>
                </div>
                
                <div class="navbar-menu">
                    <div class="navbar-end">
                        <a class="navbar-item" href="/about">
                            About
                        </a>
                        <a class="navbar-item" href="/admin">
                            Admin
                        </a>
                    </div>
                </div>
            </nav>

            `)
//line internal/web/templates/base.qtpl:39
	p.StreamBody(qw422016)
//line internal/web/templates/base.qtpl:39
	qw422016.N().S(`
        </div>
    </body>
</html>
`)
//line internal/web/templates/base.qtpl:43
}

//line internal/web/templates/base.qtpl:43
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line internal/web/templates/base.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:43
	StreamPageTemplate(qw422016, p)
//line internal/web/templates/base.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:43
}

//line internal/web/templates/base.qtpl:43
func PageTemplate(p Page) string {
//line internal/web/templates/base.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:43
	WritePageTemplate(qb422016, p)
//line internal/web/templates/base.qtpl:43
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:43
	return qs422016
//line internal/web/templates/base.qtpl:43
}

//line internal/web/templates/base.qtpl:45
type BasePage struct{}

//line internal/web/templates/base.qtpl:46
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/base.qtpl:46
	qw422016.N().S(` `)
//line internal/web/templates/base.qtpl:46
}

//line internal/web/templates/base.qtpl:46
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/base.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:46
	p.StreamTitle(qw422016)
//line internal/web/templates/base.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:46
}

//line internal/web/templates/base.qtpl:46
func (p *BasePage) Title() string {
//line internal/web/templates/base.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:46
	p.WriteTitle(qb422016)
//line internal/web/templates/base.qtpl:46
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:46
	return qs422016
//line internal/web/templates/base.qtpl:46
}

//line internal/web/templates/base.qtpl:47
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/base.qtpl:47
	qw422016.N().S(` `)
//line internal/web/templates/base.qtpl:47
}

//line internal/web/templates/base.qtpl:47
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/base.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/base.qtpl:47
	p.StreamBody(qw422016)
//line internal/web/templates/base.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/base.qtpl:47
}

//line internal/web/templates/base.qtpl:47
func (p *BasePage) Body() string {
//line internal/web/templates/base.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/base.qtpl:47
	p.WriteBody(qb422016)
//line internal/web/templates/base.qtpl:47
	qs422016 := string(qb422016.B)
//line internal/web/templates/base.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/base.qtpl:47
	return qs422016
//line internal/web/templates/base.qtpl:47
}
