// Code generated by qtc from "status.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/web/templates/status.qtpl:1
package templates

//line internal/web/templates/status.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/web/templates/status.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/web/templates/status.qtpl:2
type StatusPage struct {
	BasePage
	PageTitle string
	Header    string
	Subtitle  string
}

//line internal/web/templates/status.qtpl:10
func (p *StatusPage) StreamTitle(qw422016 *qt422016.Writer) {
//line internal/web/templates/status.qtpl:10
	qw422016.E().S(p.PageTitle)
//line internal/web/templates/status.qtpl:10
}

//line internal/web/templates/status.qtpl:10
func (p *StatusPage) WriteTitle(qq422016 qtio422016.Writer) {
//line internal/web/templates/status.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/status.qtpl:10
	p.StreamTitle(qw422016)
//line internal/web/templates/status.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/status.qtpl:10
}

//line internal/web/templates/status.qtpl:10
func (p *StatusPage) Title() string {
//line internal/web/templates/status.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/status.qtpl:10
	p.WriteTitle(qb422016)
//line internal/web/templates/status.qtpl:10
	qs422016 := string(qb422016.B)
//line internal/web/templates/status.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/status.qtpl:10
	return qs422016
//line internal/web/templates/status.qtpl:10
}

//line internal/web/templates/status.qtpl:12
func (p *StatusPage) StreamMeta(qw422016 *qt422016.Writer) {
//line internal/web/templates/status.qtpl:12
}

//line internal/web/templates/status.qtpl:12
func (p *StatusPage) WriteMeta(qq422016 qtio422016.Writer) {
//line internal/web/templates/status.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/status.qtpl:12
	p.StreamMeta(qw422016)
//line internal/web/templates/status.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/status.qtpl:12
}

//line internal/web/templates/status.qtpl:12
func (p *StatusPage) Meta() string {
//line internal/web/templates/status.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/status.qtpl:12
	p.WriteMeta(qb422016)
//line internal/web/templates/status.qtpl:12
	qs422016 := string(qb422016.B)
//line internal/web/templates/status.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/status.qtpl:12
	return qs422016
//line internal/web/templates/status.qtpl:12
}

//line internal/web/templates/status.qtpl:14
func (p *StatusPage) StreamBody(qw422016 *qt422016.Writer) {
//line internal/web/templates/status.qtpl:14
	qw422016.N().S(`
<section class="hero is-dark">
    <div class="hero-body">
        <p class="title">`)
//line internal/web/templates/status.qtpl:17
	qw422016.E().S(p.Header)
//line internal/web/templates/status.qtpl:17
	qw422016.N().S(`</p>
        <p class="subtitle">`)
//line internal/web/templates/status.qtpl:18
	qw422016.E().S(p.Subtitle)
//line internal/web/templates/status.qtpl:18
	qw422016.N().S(`</p>
    </div>
</section>
`)
//line internal/web/templates/status.qtpl:21
}

//line internal/web/templates/status.qtpl:21
func (p *StatusPage) WriteBody(qq422016 qtio422016.Writer) {
//line internal/web/templates/status.qtpl:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/web/templates/status.qtpl:21
	p.StreamBody(qw422016)
//line internal/web/templates/status.qtpl:21
	qt422016.ReleaseWriter(qw422016)
//line internal/web/templates/status.qtpl:21
}

//line internal/web/templates/status.qtpl:21
func (p *StatusPage) Body() string {
//line internal/web/templates/status.qtpl:21
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/web/templates/status.qtpl:21
	p.WriteBody(qb422016)
//line internal/web/templates/status.qtpl:21
	qs422016 := string(qb422016.B)
//line internal/web/templates/status.qtpl:21
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/web/templates/status.qtpl:21
	return qs422016
//line internal/web/templates/status.qtpl:21
}
