// Code generated by qtc from "status.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:1
package templates

//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:2
type StatusPage struct {
	BasePage
	PageTitle string
	Header    string
	Subtitle  string
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
func (p *StatusPage) StreamTitle(qw422016 *qt422016.Writer) {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
	qw422016.E().S(p.PageTitle)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
func (p *StatusPage) WriteTitle(qq422016 qtio422016.Writer) {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
	p.StreamTitle(qw422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
func (p *StatusPage) Title() string {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
	p.WriteTitle(qb422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
	qs422016 := string(qb422016.B)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
	return qs422016
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:10
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:12
func (p *StatusPage) StreamBody(qw422016 *qt422016.Writer) {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:12
	qw422016.N().S(`
<section class="hero is-black">
    <div class="hero-body">
        <p class="title">`)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:15
	qw422016.E().S(p.Header)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:15
	qw422016.N().S(`</p>
        <p class="subtitle">`)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:16
	qw422016.E().S(p.Subtitle)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:16
	qw422016.N().S(`</p>
    </div>
</section>
`)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
func (p *StatusPage) WriteBody(qq422016 qtio422016.Writer) {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
	qw422016 := qt422016.AcquireWriter(qq422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
	p.StreamBody(qw422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
	qt422016.ReleaseWriter(qw422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
}

//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
func (p *StatusPage) Body() string {
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
	qb422016 := qt422016.AcquireByteBuffer()
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
	p.WriteBody(qb422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
	qs422016 := string(qb422016.B)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
	qt422016.ReleaseByteBuffer(qb422016)
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
	return qs422016
//line /home/max/git/holedaemon/turnttable/internal/web/templates/status.qtpl:19
}
